version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile.production
    command: gunicorn -k uvicorn.workers.UvicornWorker src.web.main:app --bind=0.0.0.0:8000 --workers=3
    volumes:
      - .:/home/user/bot
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5445:5432"

  webhook_setup:
    build: .
    command: python manage.py set_webhook $(NGROK_URL)
    entrypoint: ["ngrok-entrypoint.sh"]
    depends_on:
      - ngrok
      - web

volumes:
  postgres_data:
