version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - .:/home/user/bot
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: het
    ports:
      - "5445:5432"

  ngrok:
    build: ngrok:latest
    command: http web:8000
    ports:
      - "4040:4040"
    depends_on:
      - web

volumes:
  postgres_data:
