version: "3.8"

services:
  web:
    build:
      dockerfile: Dockerfile.development
    command: gunicorn -k uvicorn.workers.UvicornWorker src.web.main:app --bind=0.0.0.0:8000 --workers=3
    volumes:
      - .:/home/user/bot
    env_file:
      - .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: het
    ports:
      - "5445:5432"

  ngrok:
    build: ngrok:latest
    command: http web:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

  webhook_setup:
    build: .
    command: python manage.py set_webhook $(NGROK_URL)
    entrypoint: ["ngrok-entrypoint.sh"]
    depends_on:
      - ngrok
      - web

volumes:
  postgres_data:
