FROM python:3.13-slim

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE=1

RUN apk update && \
    apk add --no-cache gcc musl-dev python3-dev postgresql-dev libffi-dev openssl-dev && \
    pip install --upgrade pip setuptools wheel && \
    apk add --no-cache cron

WORKDIR /app

COPY requirements/development.txt .
RUN pip install -r requirements/development.txt

COPY . .

ENTRYPOINT ["docker-entrypoint.sh"]
