FROM python:3.11.7-alpine3.19 as base

WORKDIR /home/user/het

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install dependencies
RUN apk update && \
    apk add --no-cache gcc musl-dev python3-dev postgresql-dev libffi-dev openssl-dev && \
    pip install --upgrade pip setuptools wheel

COPY requirements/development.txt .
RUN pip install -r requirements/development.txt

# Multistage for smaller final image
FROM python:3.11.7-alpine3.19

WORKDIR /home/user/het

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copy installed packages from builder stage
COPY --from=base /usr/local/lib/python3.11/ /usr/local/lib/python3.11/
COPY --from=base /usr/local/bin/ /usr/local/bin/

# Copy app code
COPY . .

# Start Bot in polling mode
CMD ["python", "-m", "src.main"]
